/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsInviteKeyRouteImport } from './routes/groups.$inviteKey'
import { Route as GroupsInviteKeyIndexRouteImport } from './routes/groups.$inviteKey.index'
import { Route as GroupsInviteKeySettlementRouteImport } from './routes/groups.$inviteKey.settlement'
import { Route as GroupsInviteKeyExpensesIndexRouteImport } from './routes/groups.$inviteKey.expenses.index'
import { Route as GroupsInviteKeyExpensesExpenseIdRouteImport } from './routes/groups.$inviteKey.expenses.$expenseId'
import { Route as GroupsInviteKeyExpensesNewRouteImport } from './routes/groups.$inviteKey.expenses.new'
import { Route as GroupsInviteKeyExpensesExpenseIdEditRouteImport } from './routes/groups.$inviteKey.expenses.$expenseId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsInviteKeyRoute = GroupsInviteKeyRouteImport.update({
  id: '/groups/$inviteKey',
  path: '/groups/$inviteKey',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsInviteKeyIndexRoute = GroupsInviteKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsInviteKeyRoute,
} as any)
const GroupsInviteKeySettlementRoute =
  GroupsInviteKeySettlementRouteImport.update({
    id: '/settlement',
    path: '/settlement',
    getParentRoute: () => GroupsInviteKeyRoute,
  } as any)
const GroupsInviteKeyExpensesIndexRoute =
  GroupsInviteKeyExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => GroupsInviteKeyRoute,
  } as any)
const GroupsInviteKeyExpensesExpenseIdRoute =
  GroupsInviteKeyExpensesExpenseIdRouteImport.update({
    id: '/expenses/$expenseId',
    path: '/expenses/$expenseId',
    getParentRoute: () => GroupsInviteKeyRoute,
  } as any)
const GroupsInviteKeyExpensesNewRoute =
  GroupsInviteKeyExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => GroupsInviteKeyRoute,
  } as any)
const GroupsInviteKeyExpensesExpenseIdEditRoute =
  GroupsInviteKeyExpensesExpenseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => GroupsInviteKeyExpensesExpenseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups/$inviteKey': typeof GroupsInviteKeyRouteWithChildren
  '/groups/$inviteKey/settlement': typeof GroupsInviteKeySettlementRoute
  '/groups/$inviteKey/': typeof GroupsInviteKeyIndexRoute
  '/groups/$inviteKey/expenses/$expenseId': typeof GroupsInviteKeyExpensesExpenseIdRouteWithChildren
  '/groups/$inviteKey/expenses/new': typeof GroupsInviteKeyExpensesNewRoute
  '/groups/$inviteKey/expenses/': typeof GroupsInviteKeyExpensesIndexRoute
  '/groups/$inviteKey/expenses/$expenseId/edit': typeof GroupsInviteKeyExpensesExpenseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups/$inviteKey/settlement': typeof GroupsInviteKeySettlementRoute
  '/groups/$inviteKey': typeof GroupsInviteKeyIndexRoute
  '/groups/$inviteKey/expenses/$expenseId': typeof GroupsInviteKeyExpensesExpenseIdRouteWithChildren
  '/groups/$inviteKey/expenses/new': typeof GroupsInviteKeyExpensesNewRoute
  '/groups/$inviteKey/expenses': typeof GroupsInviteKeyExpensesIndexRoute
  '/groups/$inviteKey/expenses/$expenseId/edit': typeof GroupsInviteKeyExpensesExpenseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/$inviteKey': typeof GroupsInviteKeyRouteWithChildren
  '/groups/$inviteKey/settlement': typeof GroupsInviteKeySettlementRoute
  '/groups/$inviteKey/': typeof GroupsInviteKeyIndexRoute
  '/groups/$inviteKey/expenses/$expenseId': typeof GroupsInviteKeyExpensesExpenseIdRouteWithChildren
  '/groups/$inviteKey/expenses/new': typeof GroupsInviteKeyExpensesNewRoute
  '/groups/$inviteKey/expenses/': typeof GroupsInviteKeyExpensesIndexRoute
  '/groups/$inviteKey/expenses/$expenseId/edit': typeof GroupsInviteKeyExpensesExpenseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/$inviteKey'
    | '/groups/$inviteKey/settlement'
    | '/groups/$inviteKey/'
    | '/groups/$inviteKey/expenses/$expenseId'
    | '/groups/$inviteKey/expenses/new'
    | '/groups/$inviteKey/expenses/'
    | '/groups/$inviteKey/expenses/$expenseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups/$inviteKey/settlement'
    | '/groups/$inviteKey'
    | '/groups/$inviteKey/expenses/$expenseId'
    | '/groups/$inviteKey/expenses/new'
    | '/groups/$inviteKey/expenses'
    | '/groups/$inviteKey/expenses/$expenseId/edit'
  id:
    | '__root__'
    | '/'
    | '/groups/$inviteKey'
    | '/groups/$inviteKey/settlement'
    | '/groups/$inviteKey/'
    | '/groups/$inviteKey/expenses/$expenseId'
    | '/groups/$inviteKey/expenses/new'
    | '/groups/$inviteKey/expenses/'
    | '/groups/$inviteKey/expenses/$expenseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsInviteKeyRoute: typeof GroupsInviteKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$inviteKey': {
      id: '/groups/$inviteKey'
      path: '/groups/$inviteKey'
      fullPath: '/groups/$inviteKey'
      preLoaderRoute: typeof GroupsInviteKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$inviteKey/': {
      id: '/groups/$inviteKey/'
      path: '/'
      fullPath: '/groups/$inviteKey/'
      preLoaderRoute: typeof GroupsInviteKeyIndexRouteImport
      parentRoute: typeof GroupsInviteKeyRoute
    }
    '/groups/$inviteKey/settlement': {
      id: '/groups/$inviteKey/settlement'
      path: '/settlement'
      fullPath: '/groups/$inviteKey/settlement'
      preLoaderRoute: typeof GroupsInviteKeySettlementRouteImport
      parentRoute: typeof GroupsInviteKeyRoute
    }
    '/groups/$inviteKey/expenses/': {
      id: '/groups/$inviteKey/expenses/'
      path: '/expenses'
      fullPath: '/groups/$inviteKey/expenses/'
      preLoaderRoute: typeof GroupsInviteKeyExpensesIndexRouteImport
      parentRoute: typeof GroupsInviteKeyRoute
    }
    '/groups/$inviteKey/expenses/$expenseId': {
      id: '/groups/$inviteKey/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/groups/$inviteKey/expenses/$expenseId'
      preLoaderRoute: typeof GroupsInviteKeyExpensesExpenseIdRouteImport
      parentRoute: typeof GroupsInviteKeyRoute
    }
    '/groups/$inviteKey/expenses/new': {
      id: '/groups/$inviteKey/expenses/new'
      path: '/expenses/new'
      fullPath: '/groups/$inviteKey/expenses/new'
      preLoaderRoute: typeof GroupsInviteKeyExpensesNewRouteImport
      parentRoute: typeof GroupsInviteKeyRoute
    }
    '/groups/$inviteKey/expenses/$expenseId/edit': {
      id: '/groups/$inviteKey/expenses/$expenseId/edit'
      path: '/edit'
      fullPath: '/groups/$inviteKey/expenses/$expenseId/edit'
      preLoaderRoute: typeof GroupsInviteKeyExpensesExpenseIdEditRouteImport
      parentRoute: typeof GroupsInviteKeyExpensesExpenseIdRoute
    }
  }
}

interface GroupsInviteKeyExpensesExpenseIdRouteChildren {
  GroupsInviteKeyExpensesExpenseIdEditRoute: typeof GroupsInviteKeyExpensesExpenseIdEditRoute
}

const GroupsInviteKeyExpensesExpenseIdRouteChildren: GroupsInviteKeyExpensesExpenseIdRouteChildren =
  {
    GroupsInviteKeyExpensesExpenseIdEditRoute:
      GroupsInviteKeyExpensesExpenseIdEditRoute,
  }

const GroupsInviteKeyExpensesExpenseIdRouteWithChildren =
  GroupsInviteKeyExpensesExpenseIdRoute._addFileChildren(
    GroupsInviteKeyExpensesExpenseIdRouteChildren,
  )

interface GroupsInviteKeyRouteChildren {
  GroupsInviteKeySettlementRoute: typeof GroupsInviteKeySettlementRoute
  GroupsInviteKeyIndexRoute: typeof GroupsInviteKeyIndexRoute
  GroupsInviteKeyExpensesExpenseIdRoute: typeof GroupsInviteKeyExpensesExpenseIdRouteWithChildren
  GroupsInviteKeyExpensesNewRoute: typeof GroupsInviteKeyExpensesNewRoute
  GroupsInviteKeyExpensesIndexRoute: typeof GroupsInviteKeyExpensesIndexRoute
}

const GroupsInviteKeyRouteChildren: GroupsInviteKeyRouteChildren = {
  GroupsInviteKeySettlementRoute: GroupsInviteKeySettlementRoute,
  GroupsInviteKeyIndexRoute: GroupsInviteKeyIndexRoute,
  GroupsInviteKeyExpensesExpenseIdRoute:
    GroupsInviteKeyExpensesExpenseIdRouteWithChildren,
  GroupsInviteKeyExpensesNewRoute: GroupsInviteKeyExpensesNewRoute,
  GroupsInviteKeyExpensesIndexRoute: GroupsInviteKeyExpensesIndexRoute,
}

const GroupsInviteKeyRouteWithChildren = GroupsInviteKeyRoute._addFileChildren(
  GroupsInviteKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsInviteKeyRoute: GroupsInviteKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
